In [3]:
from pandas import read_excel,DataFrame

In [5]:
test_file_path = "C:/Users/papasani.mohan/Pictures/TopCoder/Debitron Challenge/Testing Data/"

test_file = "testing_set.xlsx"

In [7]:
fd=DataFrame(read_excel(test_file_path+test_file))

In [8]:
del fd['BOT_JOB']

In [9]:
fd.head()

,PRODUCT_ID,AMOUNT_DUE,SAVING_ACCOUNT,CLIENT_ID,DATE,DAYS_DUE,CREDIT_BALANCE,SAVING_BALANCE,PRODUCT_DESCRIPTION,CUSTOMER_SEGMENT,...,balance51,balance52,balance53,balance54,balance55,balance56,balance57,balance58,balance59,balance60
0,4.991939e+07,1.019017e+05,5623831,349647.089431,43018,5,4.499204e+05,7.471732e+05,REESTRUC. IT. VDO. TASA FIJA,MICROPYME,...,-1161221.0,-1037937.0,308179.0,287610.0,-518425.0,-1095370.0,1039822.0,304792.0,278647.0,1412020.0
1,1.552915e+07,1.743066e+06,0-0089568-2,425392.439024,42958,44,1.684754e+07,1.883251e+06,REESTRUC. IT. VDO. TASA FIJA,PREFERENCIAL,...,1033862.0,235346.0,-1451180.0,46820.0,-419336.0,-38204.0,-1230240.0,1267150.0,1180955.0,-624761.0
2,5.014717e+08,1.389400e+05,0-0141975-3,583469.642276,42972,10,4.162013e+06,4.453994e+05,CREDIAGIL,POTENCIAL,...,-615975.0,-716836.0,1174061.0,411650.0,-763612.0,470047.0,-205796.0,-76068.0,744420.0,1234591.0
3,6.471615e+07,1.248517e+05,0-0151651-8,741712.032520,42992,11,3.611734e+06,3.040092e+05,REESTRUC. IT. VDO. TASA FIJA,ESTANDAR,...,-1230425.0,-45796.0,-226799.0,-193076.0,-900839.0,961116.0,1179674.0,475245.0,-1123570.0,-1052933.0
4,6.496007e+07,3.893303e+04,0-0151711-5,109860.260163,43007,27,4.633981e+06,1.730275e+05,COMPRA CARTERA L INVERSION,ESTANDAR,...,934280.0,-1002239.0,-1105649.0,472895.0,505495.0,1143718.0,-1105477.0,558750.0,-755117.0,1181246.0

In [13]:
fd.to_excel("testdata.xlsx")